fix(mobile): guess spaces are too hard for shell

diff --git a/apps/mobile/patches/react-native@0.70.5.patch b/apps/mobile/patches/react-native@0.70.5.patch
--- a/apps/mobile/patches/react-native@0.70.5.patch
+++ b/apps/mobile/patches/react-native@0.70.5.patch
@@ -1,21 +1,19 @@
 diff --git a/scripts/react_native_pods_utils/script_phases.sh b/scripts/react_native_pods_utils/script_phases.sh
-index 6c41ce1cbaa2b09d7b59b191b1edfb0c3fb41ea7..3df7e6c047807a7f53baf5f8703b77518e96d39a 100755
+index 6c41ce1cbaa2b09d7b59b191b1edfb0c3fb41ea7..c90834c391e8c114ebe42db939655dcc0cb12c38 100755
 --- a/scripts/react_native_pods_utils/script_phases.sh
 +++ b/scripts/react_native_pods_utils/script_phases.sh
-@@ -13,9 +13,10 @@ GENERATED_SCHEMA_FILE="$GENERATED_SRCS_DIR/schema.json"
+@@ -13,8 +13,9 @@ GENERATED_SCHEMA_FILE="$GENERATED_SRCS_DIR/schema.json"
  
  cd "$RCT_SCRIPT_RN_DIR"
  
 -CODEGEN_REPO_PATH="$RCT_SCRIPT_RN_DIR/packages/react-native-codegen"
 -CODEGEN_NPM_PATH="$RCT_SCRIPT_RN_DIR/../react-native-codegen"
--CODEGEN_CLI_PATH=""
 +# Please dont do this stuff
 +# CODEGEN_REPO_PATH="$RCT_SCRIPT_RN_DIR/packages/react-native-codegen"
 +# CODEGEN_NPM_PATH="$RCT_SCRIPT_RN_DIR/../react-native-codegen"
-+# CODEGEN_CLI_PATH=""
+ CODEGEN_CLI_PATH=""
  
  error () {
-     echo "$1"
 @@ -23,14 +24,15 @@ error () {
      exit 1
  }
@@ -39,17 +37,15 @@ index 6c41ce1cbaa2b09d7b59b191b1edfb0c3fb41ea7..3df7e6c047807a7f53baf5f8703b7751
  
  find_node () {
      NODE_BINARY="${NODE_BINARY:-$(command -v node || true)}"
-@@ -78,6 +80,15 @@ generateCodegenSchemaFromJavaScript () {
+@@ -78,6 +80,13 @@ generateCodegenSchemaFromJavaScript () {
          echo "$RCT_SCRIPT_JS_SRCS_DIR" >> "${SCRIPT_OUTPUT_FILE_0}" 2>&1
      fi
  
 +    # FML, RN is full of hardcoded paths that are incorrect when using monorepos.
 +    # Welp, guess time to rewrite some shit. If only this came "out of the box" ...
-+    CODEGEN_CLI_PATH = $("$NODE_BINARY" --print "require('path').dirname(require.resolve('react-native-codegen/package.json'))")
-+    if [ -d "$CODEGEN_CLI_PATH" ]; then
-+        # Great, continue
-+    else
-+        error "error: Could not determine react-native-codegen location in $CODEGEN_REPO_PATH or $CODEGEN_NPM_PATH. Try running 'yarn install' or 'npm install' in your project root."
++    CODEGEN_CLI_PATH=$("$NODE_BINARY" --print "require('path').dirname(require.resolve('react-native-codegen/package.json'))")
++    if ! [ -d "$CODEGEN_CLI_PATH" ]; then
++        error "error: Could not determine react-native-codegen location. Try running 'yarn install' or 'npm install' in your project root."
 +    fi
 +
      # shellcheck disable=SC2086
